--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/lovetwice1012/dailymission
build-by-default: true
branches:
- master
projects:
  gbans:
    path: "DA2D7453-1E9E-4488-B44C-C8B63C6959C1.jpeg"
...
