name: gbans-english
main: lovetwice1012\gbans\Main
version: 1.0.0
api: 
  - 3.0.0
  - 4.0.0
auther: lovetwice1012

commands:
  gban:
    description: You are a bad boy!
    usage: /gban username reason
    permission: op
  gunban:
    description: Oops.  It looks like something went wrong.  You weren't the bad guy ...
    usage: /gunban username
    permission: op
